source 'https://rubygems.org'

ruby '<%= ruby_version %>', engine: 'jruby', engine_version: '<%= engine_version %>'

gem 'nokogiri'
gem 'sinatra', '>= 2.0.0'
gem 'eventmachine'
gem 'bcrypt'
gem 'bson'

gem 'jdbc-mysql'
gem 'jdbc-postgres'
