source 'https://rubygems.org'

ruby '<%= ruby_version %>', engine: 'jruby', engine_version: '<%= engine_version %>'

gem 'nokogiri', '>= 1.11.4'
gem 'sinatra'
gem 'eventmachine'
gem 'bcrypt'
gem 'bson'

gem 'jdbc-mysql'
gem 'jdbc-postgres'
